export type VariantType = "contained" | "outlined" | "text"
export type SizeType = "xs" | "sm" | "md" | "lg" | "xl"
export type ColorType =
	| "inherit"
	| "primary"
	| "secondary"
	| "success"
	| "error"
	| "info"
	| "warning"
export type ThemeType = "dark" | "light"
export type PositionType = "top" | "bottom" | "right" | "left"

export * from "./order.types.js"
export * from "./product.types.js"
export * from "./tenant.types.js"
export * from "./toast.types.js"
export * from "./user.types.js"
export * from "./scrollSection.types.js"
