name: Release Core

on:
  push:
    tags:
      - "ff-core-v*.*.*"
    paths:
      - "packages/core/**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm run build -w @dxdns/feflow-core

      - run: npm publish -w @dxdns/feflow-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
