name: Release Vue

on:
  push:
    tags:
      - "ff-vue-v*.*.*"
    paths:
      - "packages/vue/**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm run build -w @dxdns/feflow-vue

      - run: cp README.md packages/vue

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish -w @dxdns/feflow-vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
